#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/slaves

- name: add ports to firewalld
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
  loop: "{{ ports }}"
  notify: Restart firewalld service


- name: create k3s service file
  template:
    src: k3s.service.j2
    dest: "{{ k3s_service_file }}"
    mode: '0644'
  notify: 
    - Reload systemd daemon
    - Enable and start K3s service
    