---
- hosts: mainserver
  tasks:
    - name: Set server_node_ip fact dynamically
      set_fact:
        server_node_ip: "{{ hostvars[inventory_hostname]['ansible_env'].SSH_CONNECTION.split(' ')[2] }}"

- hosts: mainserver
  become: true
  roles:
    - k3s
  tasks:
    - name: Wait for node-token file
      ansible.builtin.wait_for:
        path: /var/lib/rancher/k3s/server/node-token
        timeout: 120

    - name: Get node-token
      slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: k3s_token_raw

    - name: Set global fact for node token
      set_fact:
        k3s_node_token: "{{ k3s_token_raw['content'] | b64decode | trim }}"
      delegate_to: localhost
      run_once: true

- hosts: servers:agents
  become: true
  roles:
    - k3s
  vars:
    k3s_node_token: "{{ hostvars['mainserver']['k3s_node_token'] }}"
    server_node_ip: "{{ hostvars['mainserver']['server_node_ip'] }}"
