#SPDX-License-Identifier: MIT-0
---
# handlers file for roles/k3s
- name: Enable and start firewalld service
  service:
    name: firewalld
    state: started
    enabled: true

- name: Restart firewalld service
  service:
    name: firewalld
    state: restarted

- name: Enable and start K3s service
  service:
    name: k3s
    enabled: true
    state: started

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes
