#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/master

- name: add ports to firewalld
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
  loop: "{{ ports }}"
  notify: Restart firewalld service

- name: create k3s service file
  template:
    src: k3s.service.j2
    dest: "{{ k3s_service_file }}"
    mode: '0644'
  notify:
    - Reload systemd daemon
    - Enable and start K3s service

- name: get k3s node token
  slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: k3s_token_raw
  become: true

- name: set k3s_node_token fact
  set_fact:
    k3s_node_token: "{{ k3s_token_raw['content'] | b64decode | trim }}"
